version: "3"

services:
  api:
    build: .
    container_name: chess-data-api
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/code
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
